### ISSUE TITLE
ddb self-update fails : Text file busy

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#138]
```
$ ddb -x self-update
A new version is available: 1.4.2
Downloading |████████████████████████████████| 22072816/22072816[core:selfupdate] An unexpected error has occured [phase:selfupdate => SelfUpdateAction.execute()]: [Errno 26] Text file busy: '/home/toilal/.docker-devbox/bin/ddb'
Traceback (most recent call last):
  File "ddb/action/runner.py", line 81, in run
  File "ddb/action/runner.py", line 96, in _execute_action
  File "ddb/feature/core/actions.py", line 429, in execute
  File "ddb/feature/core/actions.py", line 462, in self_update_binary
  File "shutil.py", line 121, in copyfile
OSError: [Errno 26] Text file busy: '/home/toilal/.docker-devbox/bin/ddb'
```

**Comment by Toilal** [comment]
https://stackoverflow.com/questions/22076830/how-to-write-a-a-self-replacing-updating-binary
