### ISSUE TITLE
Issue to detect the shell in Azure Pipeline

### ISSUE THREAD

**Issue by darkanakin41** [gfi-centre-ouest/docker-devbox-ddb#22]
```
Traceback (most recent call last):
  File "ddb/__main__.py", line 497, in <module>
  File "ddb/__main__.py", line 489, in console_script
  File "ddb/__main__.py", line 422, in main
  File "ddb/__main__.py", line 207, in load_registered_features
  File "ddb/feature/feature.py", line 81, in configure
  File "ddb/config/config.py", line 129, in sanitize_and_validate
  File "ddb/feature/shell/__init__.py", line 70, in _configure_defaults
ddb.feature.feature.FeatureConfigurationAutoConfigureError: Feature "shell" has invalid configuration.
  shell: auto-configuration has failed. Please configure shell.shell manually.
[2785] Failed to execute script __main__
```

**Comment by darkanakin41** [comment]
Solution found and described in documentation 
https://github.com/gfi-centre-ouest/docker-devbox-ddb/pull/27
