### ISSUE TITLE
Bug si en mode watch

### ISSUE THREAD

**Issue by Linedev-Web** [gfi-centre-ouest/docker-devbox-ddb#49]
Si on est en mode ddb -w conffigure on ne peut pas lancer de activate ou de ddb run

```
vagrant@ubuntu-bionic:~/projects/Drupal$ cd ../                                                              
[smartcd] Deactivate                                                                                         
Traceback (most recent call last):                                                                           
  File "ddb/__main__.py", line 502, in <module>                                                              
  File "ddb/__main__.py", line 494, in console_script                                                        
  File "ddb/__main__.py", line 424, in main                                                                  
  File "ddb/__main__.py", line 215, in load_registered_features                                              
  File "ddb/__main__.py", line 192, in register_objects                                                      
  File "ddb/__main__.py", line 215, in <lambda>                                                              
  File "ddb/feature/docker/__init__.py", line 39, in actions                                                 
  File "ddb/feature/docker/actions.py", line 34, in __init__                                                 
  File "ddb/cache/__init__.py", line 23, in register_project_cache                                           
  File "ddb/cache/shelve_cache.py", line 24, in __init__                                                     
  File "shelve.py", line 243, in open                                                                        
  File "shelve.py", line 227, in __init__                                                                    
  File "dbm/__init__.py", line 94, in open                                                                   
_gdbm.error: [Errno 11] Resource temporarily unavailable                                                     
[21766] Failed to execute script __main__                                                                    
```

**Comment by Toilal** [comment]
Bizarre, j'ai pas le problème chez moi. Tu as testé @darkanakin41 ?

**Comment by Toilal** [comment]
Finalement, je reproduis le problème, avec la version compilée. J'ai l'impression que ça ne produit pas sur la version de dev.

**Comment by Toilal** [comment]
Dans la version compilée, ça utilise le module `dbm.gnu` alors que dans l'environnement de dev on a `dbm.dumb`. J'ai fait une modification pour forcer à `dbm.dumb` dans tous les cas, a test dans la version `1.0.2` en cours de release.

**Comment by Toilal** [comment]
Je confirme, c'est corrigé dans la `1.0.2` :)

**Comment by Toilal** [comment]
Bah non ça vient de me le refaire :(

**Comment by Toilal** [comment]
J'avais merdé au niveau de mon commit, y'avait pas le code qui corrige :facepalm:
