### ISSUE TITLE
ddb info error

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#87]
```
vagrant@ubuntu-bionic:~/projects/OFB-ASPE$ ddb -vv info
[docker:display-info] Execute action [phase:info => DockerDisplayInfoAction.execute()]
[docker:display-info] An unexpected error has occured [phase:info => DockerDisplayInfoAction.execute()]: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "ddb/action/runner.py", line 59, in run
  File "ddb/action/runner.py", line 74, in _execute_action
  File "ddb/feature/docker/actions.py", line 416, in execute
  File "ddb/feature/docker/actions.py", line 534, in _output_data
AttributeError: 'str' object has no attribute 'get'
```

**Comment by Toilal** [comment]
Note I use docker-compose 1.27.2 (maybe it's related)

**Comment by Toilal** [comment]
Effective config: 

```
services:
  db:
    build:
      context: /home/vagrant/projects/OFB-ASPE/.docker/db
    environment:
      POSTGRES_PASSWORD: aspe
      POSTGRES_USER: aspe
    init: true
    labels:
      ddb.emit.docker:binary[pg_dump](args): pg_dump --dbname=postgresql://aspe:aspe@db/aspe
      ddb.emit.docker:binary[pg_dump](name): pg_dump
      ddb.emit.docker:binary[pg_dump](workdir): /workdir
      ddb.emit.docker:binary[pg_dump_raw](args): pg_dump
      ddb.emit.docker:binary[pg_dump_raw](name): pg_dump_raw
      ddb.emit.docker:binary[pg_dump_raw](workdir): /workdir
      ddb.emit.docker:binary[pg_restore](args): pg_restore -h db -U aspe -d aspe
      ddb.emit.docker:binary[pg_restore](name): pg_restore
      ddb.emit.docker:binary[pg_restore](workdir): /workdir
      ddb.emit.docker:binary[pg_restore_raw](args): pg_restore
      ddb.emit.docker:binary[pg_restore_raw](name): pg_restore_raw
      ddb.emit.docker:binary[pg_restore_raw](workdir): /workdir
      ddb.emit.docker:binary[psql](args): psql --dbname=postgresql://aspe:aspe@db/aspe
      ddb.emit.docker:binary[psql](name): psql
      ddb.emit.docker:binary[psql](workdir): /workdir
      ddb.emit.docker:binary[psql_raw](args): psql
      ddb.emit.docker:binary[psql_raw](name): psql_raw
      ddb.emit.docker:binary[psql_raw](workdir): /workdir
    ports:
    - 48232:5432/tcp
    restart: "no"
    user: 1000:1000
    volumes:
    - /home/vagrant/projects/OFB-ASPE:/workdir:rw
    - db-data:/var/lib/postgresql/data:rw
    - /home/vagrant/projects/OFB-ASPE/aspe-database/init/11-aspe.schema.sql:/docker-entrypoint-initdb.d/11-aspe.schema.sql:ro
    - /home/vagrant/projects/OFB-ASPE/aspe-database/init/51-aspe.data.sql:/docker-entrypoint-initdb.d/51-aspe.data.sql:ro
  liquibase:
    build:
      context: /home/vagrant/projects/OFB-ASPE/.docker/liquibase
    environment:
      JAVA_OPTS: -Xmx4000m -Xms256m
    init: true
    labels:
      ddb.emit.docker:binary[liquibase](name): liquibase
      ddb.emit.docker:binary[liquibase](workdir): /workdir
    restart: "no"
    user: 1000:1000
    volumes:
    - /home/vagrant/projects/OFB-ASPE:/workdir:rw
version: '3.7'
volumes:
  db-data: {}
```
